//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  products: Products;
  productsConnection: ProductsConnection;
  testimonials: Testimonials;
  testimonialsConnection: TestimonialsConnection;
  faq: Faq;
  faqConnection: FaqConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProductsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProductsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductsFilter>;
};


export type QueryTestimonialsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};

export type DocumentFilter = {
  products?: InputMaybe<ProductsFilter>;
  testimonials?: InputMaybe<TestimonialsFilter>;
  faq?: InputMaybe<FaqFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Products | Testimonials | Faq | Folder;

export type ProductsProductsSizes = {
  __typename?: 'ProductsProductsSizes';
  size: Scalars['String']['output'];
  price: Scalars['Float']['output'];
};

export type ProductsProductsScent_Notes = {
  __typename?: 'ProductsProductsScent_notes';
  top?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  middle?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  base?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ProductsProducts = {
  __typename?: 'ProductsProducts';
  id: Scalars['Float']['output'];
  slug: Scalars['String']['output'];
  name: Scalars['String']['output'];
  tagline: Scalars['String']['output'];
  category: Scalars['String']['output'];
  type: Scalars['String']['output'];
  price: Scalars['Float']['output'];
  currency: Scalars['String']['output'];
  sizes?: Maybe<Array<Maybe<ProductsProductsSizes>>>;
  scent_notes?: Maybe<ProductsProductsScent_Notes>;
  vibe: Scalars['String']['output'];
  best_for?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  ingredients: Scalars['String']['output'];
  how_to_use: Scalars['String']['output'];
  warnings: Scalars['String']['output'];
  images?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
};

export type Products = Node & Document & {
  __typename?: 'Products';
  products?: Maybe<Array<Maybe<ProductsProducts>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProductsProductsSizesFilter = {
  size?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
};

export type ProductsProductsScent_NotesFilter = {
  top?: InputMaybe<StringFilter>;
  middle?: InputMaybe<StringFilter>;
  base?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProductsProductsFilter = {
  id?: InputMaybe<NumberFilter>;
  slug?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  currency?: InputMaybe<StringFilter>;
  sizes?: InputMaybe<ProductsProductsSizesFilter>;
  scent_notes?: InputMaybe<ProductsProductsScent_NotesFilter>;
  vibe?: InputMaybe<StringFilter>;
  best_for?: InputMaybe<StringFilter>;
  ingredients?: InputMaybe<StringFilter>;
  how_to_use?: InputMaybe<StringFilter>;
  warnings?: InputMaybe<StringFilter>;
  images?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  badge?: InputMaybe<StringFilter>;
};

export type ProductsFilter = {
  products?: InputMaybe<ProductsProductsFilter>;
};

export type ProductsConnectionEdges = {
  __typename?: 'ProductsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Products>;
};

export type ProductsConnection = Connection & {
  __typename?: 'ProductsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProductsConnectionEdges>>>;
};

export type TestimonialsTestimonials = {
  __typename?: 'TestimonialsTestimonials';
  id: Scalars['Float']['output'];
  name: Scalars['String']['output'];
  location: Scalars['String']['output'];
  product: Scalars['String']['output'];
  text: Scalars['String']['output'];
  rating: Scalars['Float']['output'];
};

export type Testimonials = Node & Document & {
  __typename?: 'Testimonials';
  testimonials?: Maybe<Array<Maybe<TestimonialsTestimonials>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialsTestimonialsFilter = {
  id?: InputMaybe<NumberFilter>;
  name?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  product?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
};

export type TestimonialsFilter = {
  testimonials?: InputMaybe<TestimonialsTestimonialsFilter>;
};

export type TestimonialsConnectionEdges = {
  __typename?: 'TestimonialsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonials>;
};

export type TestimonialsConnection = Connection & {
  __typename?: 'TestimonialsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialsConnectionEdges>>>;
};

export type FaqFaqs = {
  __typename?: 'FaqFaqs';
  id: Scalars['Float']['output'];
  category: Scalars['String']['output'];
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  faqs?: Maybe<Array<Maybe<FaqFaqs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqFaqsFilter = {
  id?: InputMaybe<NumberFilter>;
  category?: InputMaybe<StringFilter>;
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type FaqFilter = {
  faqs?: InputMaybe<FaqFaqsFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProducts: Products;
  createProducts: Products;
  updateTestimonials: Testimonials;
  createTestimonials: Testimonials;
  updateFaq: Faq;
  createFaq: Faq;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProductsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductsMutation;
};


export type MutationCreateProductsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductsMutation;
};


export type MutationUpdateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationCreateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};

export type DocumentUpdateMutation = {
  products?: InputMaybe<ProductsMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  faq?: InputMaybe<FaqMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  products?: InputMaybe<ProductsMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  faq?: InputMaybe<FaqMutation>;
};

export type ProductsProductsSizesMutation = {
  size?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
};

export type ProductsProductsScent_NotesMutation = {
  top?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  middle?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  base?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProductsProductsMutation = {
  id?: InputMaybe<Scalars['Float']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  currency?: InputMaybe<Scalars['String']['input']>;
  sizes?: InputMaybe<Array<InputMaybe<ProductsProductsSizesMutation>>>;
  scent_notes?: InputMaybe<ProductsProductsScent_NotesMutation>;
  vibe?: InputMaybe<Scalars['String']['input']>;
  best_for?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  ingredients?: InputMaybe<Scalars['String']['input']>;
  how_to_use?: InputMaybe<Scalars['String']['input']>;
  warnings?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
};

export type ProductsMutation = {
  products?: InputMaybe<Array<InputMaybe<ProductsProductsMutation>>>;
};

export type TestimonialsTestimonialsMutation = {
  id?: InputMaybe<Scalars['Float']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  product?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
};

export type TestimonialsMutation = {
  testimonials?: InputMaybe<Array<InputMaybe<TestimonialsTestimonialsMutation>>>;
};

export type FaqFaqsMutation = {
  id?: InputMaybe<Scalars['Float']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type FaqMutation = {
  faqs?: InputMaybe<Array<InputMaybe<FaqFaqsMutation>>>;
};

export type ProductsPartsFragment = { __typename: 'Products', products?: Array<{ __typename: 'ProductsProducts', id: number, slug: string, name: string, tagline: string, category: string, type: string, price: number, currency: string, vibe: string, best_for?: Array<string | null> | null, ingredients: string, how_to_use: string, warnings: string, images?: Array<string | null> | null, featured?: boolean | null, badge?: string | null, sizes?: Array<{ __typename: 'ProductsProductsSizes', size: string, price: number } | null> | null, scent_notes?: { __typename: 'ProductsProductsScent_notes', top?: Array<string | null> | null, middle?: Array<string | null> | null, base?: Array<string | null> | null } | null } | null> | null };

export type TestimonialsPartsFragment = { __typename: 'Testimonials', testimonials?: Array<{ __typename: 'TestimonialsTestimonials', id: number, name: string, location: string, product: string, text: string, rating: number } | null> | null };

export type FaqPartsFragment = { __typename: 'Faq', faqs?: Array<{ __typename: 'FaqFaqs', id: number, category: string, question: string, answer: string } | null> | null };

export type ProductsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProductsQuery = { __typename?: 'Query', products: { __typename: 'Products', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, products?: Array<{ __typename: 'ProductsProducts', id: number, slug: string, name: string, tagline: string, category: string, type: string, price: number, currency: string, vibe: string, best_for?: Array<string | null> | null, ingredients: string, how_to_use: string, warnings: string, images?: Array<string | null> | null, featured?: boolean | null, badge?: string | null, sizes?: Array<{ __typename: 'ProductsProductsSizes', size: string, price: number } | null> | null, scent_notes?: { __typename: 'ProductsProductsScent_notes', top?: Array<string | null> | null, middle?: Array<string | null> | null, base?: Array<string | null> | null } | null } | null> | null } };

export type ProductsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductsFilter>;
}>;


export type ProductsConnectionQuery = { __typename?: 'Query', productsConnection: { __typename?: 'ProductsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProductsConnectionEdges', cursor: string, node?: { __typename: 'Products', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, products?: Array<{ __typename: 'ProductsProducts', id: number, slug: string, name: string, tagline: string, category: string, type: string, price: number, currency: string, vibe: string, best_for?: Array<string | null> | null, ingredients: string, how_to_use: string, warnings: string, images?: Array<string | null> | null, featured?: boolean | null, badge?: string | null, sizes?: Array<{ __typename: 'ProductsProductsSizes', size: string, price: number } | null> | null, scent_notes?: { __typename: 'ProductsProductsScent_notes', top?: Array<string | null> | null, middle?: Array<string | null> | null, base?: Array<string | null> | null } | null } | null> | null } | null } | null> | null } };

export type TestimonialsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialsQuery = { __typename?: 'Query', testimonials: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonials?: Array<{ __typename: 'TestimonialsTestimonials', id: number, name: string, location: string, product: string, text: string, rating: number } | null> | null } };

export type TestimonialsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
}>;


export type TestimonialsConnectionQuery = { __typename?: 'Query', testimonialsConnection: { __typename?: 'TestimonialsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialsConnectionEdges', cursor: string, node?: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonials?: Array<{ __typename: 'TestimonialsTestimonials', id: number, name: string, location: string, product: string, text: string, rating: number } | null> | null } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqQuery = { __typename?: 'Query', faq: { __typename: 'Faq', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'FaqFaqs', id: number, category: string, question: string, answer: string } | null> | null } };

export type FaqConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
}>;


export type FaqConnectionQuery = { __typename?: 'Query', faqConnection: { __typename?: 'FaqConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqConnectionEdges', cursor: string, node?: { __typename: 'Faq', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'FaqFaqs', id: number, category: string, question: string, answer: string } | null> | null } | null } | null> | null } };

export const ProductsPartsFragmentDoc = gql`
    fragment ProductsParts on Products {
  __typename
  products {
    __typename
    id
    slug
    name
    tagline
    category
    type
    price
    currency
    sizes {
      __typename
      size
      price
    }
    scent_notes {
      __typename
      top
      middle
      base
    }
    vibe
    best_for
    ingredients
    how_to_use
    warnings
    images
    featured
    badge
  }
}
    `;
export const TestimonialsPartsFragmentDoc = gql`
    fragment TestimonialsParts on Testimonials {
  __typename
  testimonials {
    __typename
    id
    name
    location
    product
    text
    rating
  }
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  faqs {
    __typename
    id
    category
    question
    answer
  }
}
    `;
export const ProductsDocument = gql`
    query products($relativePath: String!) {
  products(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProductsParts
  }
}
    ${ProductsPartsFragmentDoc}`;
export const ProductsConnectionDocument = gql`
    query productsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProductsFilter) {
  productsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProductsParts
      }
    }
  }
}
    ${ProductsPartsFragmentDoc}`;
export const TestimonialsDocument = gql`
    query testimonials($relativePath: String!) {
  testimonials(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialsParts
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const TestimonialsConnectionDocument = gql`
    query testimonialsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialsFilter) {
  testimonialsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialsParts
      }
    }
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      products(variables: ProductsQueryVariables, options?: C): Promise<{data: ProductsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsQueryVariables, query: string}> {
        return requester<{data: ProductsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsQueryVariables, query: string}, ProductsQueryVariables>(ProductsDocument, variables, options);
      },
    productsConnection(variables?: ProductsConnectionQueryVariables, options?: C): Promise<{data: ProductsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsConnectionQueryVariables, query: string}> {
        return requester<{data: ProductsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsConnectionQueryVariables, query: string}, ProductsConnectionQueryVariables>(ProductsConnectionDocument, variables, options);
      },
    testimonials(variables: TestimonialsQueryVariables, options?: C): Promise<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}> {
        return requester<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}, TestimonialsQueryVariables>(TestimonialsDocument, variables, options);
      },
    testimonialsConnection(variables?: TestimonialsConnectionQueryVariables, options?: C): Promise<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}, TestimonialsConnectionQueryVariables>(TestimonialsConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  